name: deploy-book

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install Mamba environment
    - name: Install Mamba environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml

    # Build the book
    - name: Build the book
      run: |
        micromamba activate blog
        jupyter-book clean . --all
        jupyter-book build .

    # Push the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html